1.

export class PagePath {
  static readonly entry_a = "/entry/a"
  static readonly entry_b = "entry/b"
  static readonly entry_c = "entry/c"
  static readonly entry_d = "/entry/d/"
  static readonly entry_e = "entry_E"
  static readonly entry_f = "/entry_F"
  static readonly entry_g = "entry_G/"
  static readonly entry_test = "/entry/test/0"
  static readonly entry_test1 = "/entry/test1/1/"
  static readonly entry_test2 = "entry/test2/2/"
  static readonly hara_a = "/hara/a"
  static readonly hara_b = "hara/b"
  static readonly hara_c = "hara/c/"
  static readonly hara_d = "/hara/d/"
  static readonly hara_e = "hara_E"
  static readonly hara_f = "/hara_F"
  static readonly hara_g = "hara_G/"
  static readonly hara_test = "/hara/test/0"
  static readonly hara_test1 = "/hara/test1/1/"
  static readonly hara_test2 = "hara/test2/2/"
  static readonly harb_b = "harb/b"
  static readonly hspc_c = "hspc/c/"
}

2.
      const privateKey_1024 = `-----BEGIN PRIVATE KEY-----
MIIBUwIBADANBgkqhkiG9w0BAQEFAASCAT0wggE5AgEAAkEAnpq5AnKbU5zTBf6G
6aER0TQhlKw3OpOswmY2ATKI/iW1KFM2EgVYjqbZebZk44RUd3Hf0MtxsrQfLs97
K17bvwIDAQABAkBg4WHhfOAkUscUAkWmsBySDaX1iryxq0L7/DNAx/2mP6wYFPFT
hzosy+YC2q0CKX2Dl9Cm4pPX1pJc17jud4kBAiEAzB8uifwTZrFLn5vVv21F1L9D
+YE0pfbPBZhTgHyaVYsCIQDG6ggq5/MVwKseWeH6M5ftUiJPgJQrVbb91niQ2Jzh
HQIgT0REpFz5g8WR4nd3uBDNL2LfGMMuGM0Rc9DFjH3WySUCIDVsshjkB3P2NX+H
YJxUsx94ieKUhDdHZEi1C9jLdQc5AiBrqf/4wDLWKoS8ANz+GorOZg1gfRASZL1b
LXpSotIB5w==
-----END PRIVATE KEY-----
`

3.

import { OneSubPageFrame } from "@one/page-frame";

@ComponentV2
export struct SettingDownloadManage {
  build() {
    OneSubPageFrame() {
      
    }
  }
}

4.

export default class OtherSine{
  public data:number[]=[
    0.0,//#0
    0.09983341664682815,//#1
    0.19866933079506122,//#2
    0.2955202066613396,//#3
    0.3894183423086505,//#4
    0.479425538604203,//#5
    0.5646424733950354,//#6
    0.644217687237691,//#7
    0.7173560908995227,//#8
    0.7833269096274833,//#9
    0.8414709848078964,//#10
    0.8912073600614353,//#11
    0.9320390859672263,//#12
    0.963558185417193,//#13
    0.9854497299884603,//#14
    0.9974949866040544,//#15
    0.9995736030415051,//#16
    0.9916648104524686,//#17
    0.973847630878195,//#18
    0.9463000876874144,//#19
    0.9092974268256815,//#20
    0.8632093666488735,//#21
    0.8084964038195899,//#22
    0.7457052121767197,//#23
    0.6754631805511504,//#24